site_name: Qkmaxware.Numerics
site_url: http://qkmaxware.github.io/Numerics/

docs_dir: docs/
site_dir: site/

repo_name: GitHub
repo_url: https://github.com/qkmaxware/Numerics

theme: 
  name: readthedocs
  custom_dir: docs_theme/

plugins:
  - awesome-pages
  - search

markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      macro-file: macros.tex
